[package]
name = "bikechain"
version = "0.1.0"
authors = ["Jerome Gagnon <jerome.gagnon.1@gmail.com>"]

[dependencies]
chrono = "0.4"
rust-crypto = "0.2.36"
serde = "1.0.15"
serde_derive = "1.0.15"
bincode = "0.9.2"