[package]
name = "bikechain"
version = "0.1.0"
authors = ["Jerome Gagnon <jerome.gagnon.1@gmail.com>"]

[dependencies]
chrono = "0.4"
rocket = "0.3"
rocket_codegen = "0.3"
rust-crypto = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bincode = "0.9.2"